### PR TITLE
changed requirements.txt to specific diffuser version 0.30.0, fixes issue #123

### PR DESCRIPTION
**Pull request by ewandel**
See this issue: https://github.com/ostris/ai-toolkit/issues/123

This avoids an error message when running when using the latest (as of 22 August 2024) diffuser version:

not working diffuser version: 0.31.0.dev0
Error message: Error running job: cannot import name 'apply_rope' from 'diffusers.models.attention_processor'

### CODE REVIEW

**Comment by jaretburkett** [comment]
Thank you. There was a breaking change in diffusers, but it is fixed with https://github.com/ostris/ai-toolkit/commit/338c77d67733a2d6d9c4fdd55623ae04f5ed5ead . I plan to switch to the packaged version as soon as all the flux code stabilizes.
